site_name: 'test'
site_description: 'Documentation'

nav:
  - Intro: sdk/collections.md
  - Mars Utils: sdk/mars_utils.ipynb

plugins:
  - techdocs-core
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: false
            docstring_style: sphinx
            show_root_heading: true
            show_source: false
            heading_level: 2
            show_signature: false
            show_root_full_path: false
            show_signature_annotations: true
            docstring_section_style: table
extra_css: [test.css]
